name: Build pull request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  #build-pull-request-python:
  build-pull-request-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build the Docker image with the latest tag and the release tag
      - name: Build and push Docker image with latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: uugai/uugai-python-dynamic-queue:latest
